### ISSUE TITLE
Error when updating user

### ISSUE THREAD

**Issue by chrisbartoloburlo** [Throyer/springboot-api-crud#17]
I am getting the following error when attempting to update a user:
`"status":500,"error":"Internal Server Error","trace":"org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing`

Steps to reproduce it:
1. `curl -H 'Content-Type: application/json' -d '{"email":"admin@email.com","password":"admin"}' localhost:8080/api/sessions`
2. `curl  -H 'Content-Type: application/json' -d '{"name":"name1","email":"name1@email.com","password":"12345678"}' -H "Authorization: Bearer <token>" localhost:8080/api/users/`
3. `curl -X PUT -H 'Content-Type: application/json' -d '{"name":"chris2","email":"chris2@email.com"}' -H "Authorization: Bearer <token>" localhost:8080/api/users/{id}`

Am I doing something wrong? Or is this a bug in the application? 
Thanks!

**Comment by Throyer** [comment]
Hi, I fixed the problem.
This error happened because the user was loaded without their roles in the update service, and when trying to update the information the role objects that had loaded only the initials caused an error in hibernate

if you wanted to see in more details: https://github.com/Throyer/springboot-api-rest-example/commit/969baec5d670e08c4739de4f0bd3770d0a8cc217

Thanks for reporting the bug 😁
